// frontend-vue/src/components/DatosEmpleado.vue
<script setup>
import { reactive, ref } from 'vue';
import { updateMe } from '../lib/api.js';

const props = defineProps({ user: { type: Object, required: true } });
const emit = defineEmits(['update']);

const CAMPOS = [
  { id: 'nombre', label: 'Nombre' },
  { id: 'email', label: 'Email' },
  { id: 'telefono', label: 'Teléfono' },
  { id: 'puesto', label: 'Puesto' },
  { id: 'departamento', label: 'Departamento' },
  { id: 'direccion', label: 'Dirección' },
  { id: 'foto', label: 'Foto (URL)' },
];

const form = reactive({
  nombre: props.user.nombre ?? '',
  email: props.user.email ?? '',
  telefono: props.user.telefono ?? '',
  puesto: props.user.puesto ?? '',
  departamento: props.user.departamento ?? '',
  direccion: props.user.direccion ?? '',
  foto: props.user.foto ?? '',
});

const estado = ref(null); // null | 'ok' | 'error'
const busy = ref(false);

async function guardar() {
  busy.value = true;
  try {
    const actualizado = await updateMe({ ...form });
    emit('update', actualizado);
    estado.value = 'ok';
  } catch {
    estado.value = 'error';
  } finally {
    busy.value = false;
  }
}
</script>

<template>
  <div class="perfil">
    <div class="perfil-foto-col">
      <img
        class="perfil-foto"
        :src="form.foto || 'data:image/svg+xml,<svg xmlns=&quot;http://www.w3.org/2000/svg&quot;/>'"
        :alt="form.nombre || 'Foto de perfil'"
      />
    </div>
    <form class="perfil-form" @submit.prevent="guardar">
      <div v-for="c in CAMPOS" :key="c.id" class="perfil-campo">
        <label :for="`campo-${c.id}`">{{ c.label }}</label>
        <input :id="`campo-${c.id}`" v-model="form[c.id]" @input="estado = null" />
      </div>
      <div class="perfil-acciones">
        <button type="submit" :disabled="busy">Guardar</button>
        <span v-if="estado === 'ok'" class="perfil-ok">Cambios guardados ✓</span>
        <span v-if="estado === 'error'" class="perfil-error">No se pudo guardar</span>
      </div>
    </form>
  </div>
</template>

// frontend-react/src/components/DatosEmpleado.jsx
import { useState } from 'react';
import { updateMe } from '../lib/api.js';

const CAMPOS = [
  { id: 'nombre', label: 'Nombre' },
  { id: 'email', label: 'Email' },
  { id: 'telefono', label: 'Teléfono' },
  { id: 'puesto', label: 'Puesto' },
  { id: 'departamento', label: 'Departamento' },
  { id: 'direccion', label: 'Dirección' },
  { id: 'foto', label: 'Foto (URL)' },
];

export default function DatosEmpleado({ user, onUpdate }) {
  const [form, setForm] = useState({
    nombre: user.nombre ?? '',
    email: user.email ?? '',
    telefono: user.telefono ?? '',
    puesto: user.puesto ?? '',
    departamento: user.departamento ?? '',
    direccion: user.direccion ?? '',
    foto: user.foto ?? '',
  });
  const [estado, setEstado] = useState(null); // null | 'ok' | 'error'
  const [busy, setBusy] = useState(false);

  function setCampo(id, value) {
    setForm((f) => ({ ...f, [id]: value }));
    setEstado(null);
  }

  async function guardar(e) {
    e.preventDefault();
    setBusy(true);
    try {
      const actualizado = await updateMe(form);
      onUpdate(actualizado);
      setEstado('ok');
    } catch {
      setEstado('error');
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="perfil">
      <div className="perfil-foto-col">
        <img
          className="perfil-foto"
          src={form.foto || 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg"/>'}
          alt={form.nombre || 'Foto de perfil'}
        />
      </div>
      <form className="perfil-form" onSubmit={guardar}>
        {CAMPOS.map((c) => (
          <div className="perfil-campo" key={c.id}>
            <label htmlFor={`campo-${c.id}`}>{c.label}</label>
            <input
              id={`campo-${c.id}`}
              value={form[c.id]}
              onChange={(e) => setCampo(c.id, e.target.value)}
            />
          </div>
        ))}
        <div className="perfil-acciones">
          <button type="submit" disabled={busy}>Guardar</button>
          {estado === 'ok' && <span className="perfil-ok">Cambios guardados ✓</span>}
          {estado === 'error' && <span className="perfil-error">No se pudo guardar</span>}
        </div>
      </form>
    </div>
  );
}
