// frontend-vue/src/components/Login.vue
<script setup>
import { ref } from 'vue';
import { login } from '../lib/api.js';
import Logo from './Logo.vue';

const emit = defineEmits(['login']);

const username = ref('');
const password = ref('');
const error = ref('');
const busy = ref(false);

async function submit() {
  busy.value = true;
  error.value = '';
  try {
    const user = await login(username.value, password.value);
    emit('login', user);
  } catch (err) {
    error.value = err.status === 401
      ? 'Usuario o contraseña no válidos'
      : 'No se pudo conectar con el servidor';
  } finally {
    busy.value = false;
  }
}
</script>

<template>
  <div class="login-page">
    <Logo class="login-logo" />
    <h1 class="login-title">Acceso al<br />Portal del Empleado</h1>
    <form class="login-form" @submit.prevent="submit">
      <input v-model="username" placeholder="Usuario" autofocus />
      <input v-model="password" type="password" placeholder="Contraseña" />
      <button type="submit" :disabled="busy">Entrar</button>
      <p class="login-error">{{ error }}</p>
    </form>
    <div class="login-version">PEN version 2.9.5</div>
    <div class="login-copy">Nunegal Consulting ©</div>
  </div>
</template>

// frontend-react/src/components/Login.jsx
import { useState } from 'react';
import { login } from '../lib/api.js';
import Logo from './Logo.jsx';

export default function Login({ onLogin }) {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);

  async function submit(e) {
    e.preventDefault();
    setBusy(true);
    setError('');
    try {
      const user = await login(username, password);
      onLogin(user);
    } catch (err) {
      setError(err.status === 401 ? 'Usuario o contraseña no válidos' : 'No se pudo conectar con el servidor');
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="login-page">
      <Logo className="login-logo" />
      <h1 className="login-title">Acceso al<br />Portal del Empleado</h1>
      <form className="login-form" onSubmit={submit}>
        <input
          placeholder="Usuario"
          value={username}
          onChange={(e) => setUsername(e.target.value)}
          autoFocus
        />
        <input
          type="password"
          placeholder="Contraseña"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
        />
        <button type="submit" disabled={busy}>Entrar</button>
        <p className="login-error">{error}</p>
      </form>
      <div className="login-version">PEN version 2.9.5</div>
      <div className="login-copy">Nunegal Consulting ©</div>
    </div>
  );
}
