// frontend-react/src/components/Conocimientos.jsx
import { useEffect, useMemo, useState } from 'react';
import {
  listCertificaciones, createCertificacion, updateCertificacion, deleteCertificacion,
} from '../lib/api.js';

const COLUMNAS = [
  { id: 'conocimiento', label: 'Conocimiento / Certificación', sortable: true, izq: true },
  { id: 'empresaEmisora', label: 'Empresa emisora', sortable: true },
  { id: 'fecha', label: 'Fecha', sortable: true },
];

const VACIA = { conocimiento: '', empresaEmisora: '', fecha: '' };

export default function Conocimientos() {
  const [items, setItems] = useState([]);
  const [cargando, setCargando] = useState(true);
  const [error, setError] = useState('');

  const [buscar, setBuscar] = useState('');
  const [pageSize, setPageSize] = useState(10);
  const [page, setPage] = useState(1);
  const [sort, setSort] = useState({ campo: 'conocimiento', dir: 'asc' });

  const [editando, setEditando] = useState(null); // null | {id?, conocimiento, ...}
  const [borrando, setBorrando] = useState(null); // null | item

  async function recargar() {
    setCargando(true);
    setError('');
    try {
      setItems(await listCertificaciones());
    } catch {
      setError('No se pudieron cargar las certificaciones');
    } finally {
      setCargando(false);
    }
  }

  useEffect(() => { recargar(); }, []);

  const filtradas = useMemo(() => {
    const q = buscar.trim().toLowerCase();
    let arr = items;
    if (q) {
      arr = arr.filter((c) =>
        [c.conocimiento, c.empresaEmisora, c.fecha]
          .some((v) => (v ?? '').toLowerCase().includes(q)));
    }
    const { campo, dir } = sort;
    arr = [...arr].sort((a, b) => {
      const r = String(a[campo] ?? '').localeCompare(String(b[campo] ?? ''), 'es', { numeric: true });
      return dir === 'asc' ? r : -r;
    });
    return arr;
  }, [items, buscar, sort]);

  const total = filtradas.length;
  const totalPages = Math.max(1, Math.ceil(total / pageSize));
  const pageActual = Math.min(page, totalPages);
  const inicio = total === 0 ? 0 : (pageActual - 1) * pageSize;
  const visibles = filtradas.slice(inicio, inicio + pageSize);

  function cambiarSort(campo) {
    setSort((s) => (s.campo === campo
      ? { campo, dir: s.dir === 'asc' ? 'desc' : 'asc' }
      : { campo, dir: 'asc' }));
  }

  async function guardar(datos) {
    if (editando.id) {
      await updateCertificacion(editando.id, datos);
    } else {
      await createCertificacion(datos);
    }
    setEditando(null);
    await recargar();
  }

  async function confirmarBorrado() {
    await deleteCertificacion(borrando.id);
    setBorrando(null);
    await recargar();
  }

  return (
    <div>
      <div className="cert-top">
        <div className="cert-mostrar">
          Mostrar
          <select
            value={pageSize}
            onChange={(e) => { setPageSize(Number(e.target.value)); setPage(1); }}
          >
            {[10, 25, 50].map((n) => <option key={n} value={n}>{n}</option>)}
          </select>
          registros
        </div>
        <label className="cert-buscar">
          Buscar:
          <input
            value={buscar}
            onChange={(e) => { setBuscar(e.target.value); setPage(1); }}
          />
        </label>
      </div>

      <table className="cert-tabla">
        <thead>
          <tr>
            {COLUMNAS.map((col) => {
              const activo = sort.campo === col.id;
              return (
                <th
                  key={col.id}
                  className={`${col.sortable ? 'sortable ' : ''}${col.izq ? 'cert-col-conocimiento' : ''}`}
                  onClick={col.sortable ? () => cambiarSort(col.id) : undefined}
                >
                  {col.label}
                  {col.sortable && (
                    <span className={`cert-sort${activo ? ' activo' : ''}`}>
                      {activo ? (sort.dir === 'asc' ? '▲' : '▼') : '⇅'}
                    </span>
                  )}
                </th>
              );
            })}
            <th>Opciones</th>
          </tr>
        </thead>
        <tbody>
          {cargando && (
            <tr><td className="cert-vacio" colSpan={4}>Cargando…</td></tr>
          )}
          {!cargando && error && (
            <tr><td className="cert-vacio" colSpan={4}>{error}</td></tr>
          )}
          {!cargando && !error && visibles.length === 0 && (
            <tr><td className="cert-vacio" colSpan={4}>No hay registros disponibles</td></tr>
          )}
          {!cargando && !error && visibles.map((c) => (
            <tr key={c.id}>
              <td className="cert-col-conocimiento">{c.conocimiento}</td>
              <td>{c.empresaEmisora}</td>
              <td>{c.fecha}</td>
              <td>
                <div className="cert-acciones">
                  <button className="cert-icono" title="Editar" onClick={() => setEditando(c)}>✏️</button>
                  <button className="cert-icono borrar" title="Eliminar" onClick={() => setBorrando(c)}>🗑️</button>
                </div>
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      <div className="cert-footer">
        <div className="cert-info">
          {total === 0
            ? 'Mostrando 0 de 0 registros'
            : `Mostrando ${inicio + 1} a ${Math.min(inicio + pageSize, total)} de un total de ${total} registros`}
        </div>
        <div className="cert-paginacion">
          <button
            className="cert-pag"
            disabled={pageActual <= 1}
            onClick={() => setPage(pageActual - 1)}
          >
            ‹
          </button>
          {Array.from({ length: totalPages }, (_, i) => i + 1).map((n) => (
            <button
              key={n}
              className={`cert-pag${n === pageActual ? ' activo' : ''}`}
              onClick={() => setPage(n)}
            >
              {n}
            </button>
          ))}
          <button
            className="cert-pag"
            disabled={pageActual >= totalPages}
            onClick={() => setPage(pageActual + 1)}
          >
            ›
          </button>
        </div>
      </div>

      <button className="cert-anadir" onClick={() => setEditando({ ...VACIA })}>Añadir</button>

      {editando && (
        <FormularioModal
          inicial={editando}
          onCancel={() => setEditando(null)}
          onSave={guardar}
        />
      )}

      {borrando && (
        <div className="modal-overlay" onClick={() => setBorrando(null)}>
          <div className="modal" onClick={(e) => e.stopPropagation()}>
            <div className="modal-head">Eliminar certificación</div>
            <div className="modal-texto">
              ¿Seguro que quieres eliminar «{borrando.conocimiento}»?
            </div>
            <div className="modal-foot">
              <button className="btn" onClick={() => setBorrando(null)}>Cancelar</button>
              <button className="btn btn-danger" onClick={confirmarBorrado}>Eliminar</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function FormularioModal({ inicial, onCancel, onSave }) {
  const [form, setForm] = useState({
    conocimiento: inicial.conocimiento ?? '',
    empresaEmisora: inicial.empresaEmisora ?? '',
    fecha: inicial.fecha ?? '',
  });
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');

  const set = (k, v) => setForm((f) => ({ ...f, [k]: v }));

  async function submit(e) {
    e.preventDefault();
    if (!form.conocimiento.trim()) {
      setError('El conocimiento / certificación es obligatorio');
      return;
    }
    setBusy(true);
    setError('');
    try {
      await onSave(form);
    } catch {
      setError('No se pudo guardar');
      setBusy(false);
    }
  }

  return (
    <div className="modal-overlay" onClick={onCancel}>
      <form className="modal" onClick={(e) => e.stopPropagation()} onSubmit={submit}>
        <div className="modal-head">{inicial.id ? 'Editar certificación' : 'Nueva certificación'}</div>
        <div className="modal-body">
          <div className="modal-campo">
            <label htmlFor="m-conocimiento">Conocimiento / Certificación</label>
            <input
              id="m-conocimiento"
              value={form.conocimiento}
              onChange={(e) => set('conocimiento', e.target.value)}
              autoFocus
            />
          </div>
          <div className="modal-campo">
            <label htmlFor="m-empresa">Empresa emisora</label>
            <input
              id="m-empresa"
              value={form.empresaEmisora}
              onChange={(e) => set('empresaEmisora', e.target.value)}
            />
          </div>
          <div className="modal-campo">
            <label htmlFor="m-fecha">Fecha</label>
            <input
              id="m-fecha"
              type="date"
              value={form.fecha}
              onChange={(e) => set('fecha', e.target.value)}
            />
          </div>
          {error && <span className="perfil-error">{error}</span>}
        </div>
        <div className="modal-foot">
          <button type="button" className="btn" onClick={onCancel}>Cancelar</button>
          <button type="submit" className="btn btn-primary" disabled={busy}>Guardar</button>
        </div>
      </form>
    </div>
  );
}

// frontend-vue/src/components/Conocimientos.vue
<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import {
  listCertificaciones, createCertificacion, updateCertificacion, deleteCertificacion,
} from '../lib/api.js';

const COLUMNAS = [
  { id: 'conocimiento', label: 'Conocimiento / Certificación', sortable: true, izq: true },
  { id: 'empresaEmisora', label: 'Empresa emisora', sortable: true },
  { id: 'fecha', label: 'Fecha', sortable: true },
];

const items = ref([]);
const cargando = ref(true);
const error = ref('');

const buscar = ref('');
const pageSize = ref(10);
const page = ref(1);
const sort = reactive({ campo: 'conocimiento', dir: 'asc' });

const editando = ref(null); // null | {id?, conocimiento, ...}
const borrando = ref(null); // null | item

// Modal de formulario
const form = reactive({ conocimiento: '', empresaEmisora: '', fecha: '' });
const formBusy = ref(false);
const formError = ref('');

async function recargar() {
  cargando.value = true;
  error.value = '';
  try {
    items.value = await listCertificaciones();
  } catch {
    error.value = 'No se pudieron cargar las certificaciones';
  } finally {
    cargando.value = false;
  }
}

onMounted(recargar);

const filtradas = computed(() => {
  const q = buscar.value.trim().toLowerCase();
  let arr = items.value;
  if (q) {
    arr = arr.filter((c) =>
      [c.conocimiento, c.empresaEmisora, c.fecha]
        .some((v) => (v ?? '').toLowerCase().includes(q)));
  }
  arr = [...arr].sort((a, b) => {
    const r = String(a[sort.campo] ?? '').localeCompare(String(b[sort.campo] ?? ''), 'es', { numeric: true });
    return sort.dir === 'asc' ? r : -r;
  });
  return arr;
});

const total = computed(() => filtradas.value.length);
const totalPages = computed(() => Math.max(1, Math.ceil(total.value / pageSize.value)));
const pageActual = computed(() => Math.min(page.value, totalPages.value));
const inicio = computed(() => (total.value === 0 ? 0 : (pageActual.value - 1) * pageSize.value));
const visibles = computed(() => filtradas.value.slice(inicio.value, inicio.value + pageSize.value));
const paginas = computed(() => Array.from({ length: totalPages.value }, (_, i) => i + 1));

function cambiarSort(col) {
  if (!col.sortable) return;
  if (sort.campo === col.id) {
    sort.dir = sort.dir === 'asc' ? 'desc' : 'asc';
  } else {
    sort.campo = col.id;
    sort.dir = 'asc';
  }
}

function abrirNuevo() {
  editando.value = {};
  Object.assign(form, { conocimiento: '', empresaEmisora: '', fecha: '' });
  formError.value = '';
}

function abrirEditar(c) {
  editando.value = c;
  Object.assign(form, {
    conocimiento: c.conocimiento ?? '',
    empresaEmisora: c.empresaEmisora ?? '',
    fecha: c.fecha ?? '',
  });
  formError.value = '';
}

async function guardar() {
  if (!form.conocimiento.trim()) {
    formError.value = 'El conocimiento / certificación es obligatorio';
    return;
  }
  formBusy.value = true;
  formError.value = '';
  try {
    const datos = { ...form };
    if (editando.value.id) {
      await updateCertificacion(editando.value.id, datos);
    } else {
      await createCertificacion(datos);
    }
    editando.value = null;
    await recargar();
  } catch {
    formError.value = 'No se pudo guardar';
  } finally {
    formBusy.value = false;
  }
}

async function confirmarBorrado() {
  await deleteCertificacion(borrando.value.id);
  borrando.value = null;
  await recargar();
}
</script>

<template>
  <div>
    <div class="cert-top">
      <div class="cert-mostrar">
        Mostrar
        <select v-model.number="pageSize" @change="page = 1">
          <option v-for="n in [10, 25, 50]" :key="n" :value="n">{{ n }}</option>
        </select>
        registros
      </div>
      <label class="cert-buscar">
        Buscar:
        <input v-model="buscar" @input="page = 1" />
      </label>
    </div>

    <table class="cert-tabla">
      <thead>
        <tr>
          <th
            v-for="col in COLUMNAS"
            :key="col.id"
            :class="[{ sortable: col.sortable }, col.izq ? 'cert-col-conocimiento' : '']"
            @click="cambiarSort(col)"
          >
            {{ col.label }}
            <span v-if="col.sortable" class="cert-sort" :class="{ activo: sort.campo === col.id }">
              {{ sort.campo === col.id ? (sort.dir === 'asc' ? '▲' : '▼') : '⇅' }}
            </span>
          </th>
          <th>Opciones</th>
        </tr>
      </thead>
      <tbody>
        <tr v-if="cargando"><td class="cert-vacio" colspan="4">Cargando…</td></tr>
        <tr v-else-if="error"><td class="cert-vacio" colspan="4">{{ error }}</td></tr>
        <tr v-else-if="visibles.length === 0"><td class="cert-vacio" colspan="4">No hay registros disponibles</td></tr>
        <tr v-else v-for="c in visibles" :key="c.id">
          <td class="cert-col-conocimiento">{{ c.conocimiento }}</td>
          <td>{{ c.empresaEmisora }}</td>
          <td>{{ c.fecha }}</td>
          <td>
            <div class="cert-acciones">
              <button class="cert-icono" title="Editar" @click="abrirEditar(c)">✏️</button>
              <button class="cert-icono borrar" title="Eliminar" @click="borrando = c">🗑️</button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>

    <div class="cert-footer">
      <div class="cert-info">
        <template v-if="total === 0">Mostrando 0 de 0 registros</template>
        <template v-else>
          Mostrando {{ inicio + 1 }} a {{ Math.min(inicio + pageSize, total) }} de un total de {{ total }} registros
        </template>
      </div>
      <div class="cert-paginacion">
        <button class="cert-pag" :disabled="pageActual <= 1" @click="page = pageActual - 1">‹</button>
        <button
          v-for="n in paginas"
          :key="n"
          class="cert-pag"
          :class="{ activo: n === pageActual }"
          @click="page = n"
        >
          {{ n }}
        </button>
        <button class="cert-pag" :disabled="pageActual >= totalPages" @click="page = pageActual + 1">›</button>
      </div>
    </div>

    <button class="cert-anadir" @click="abrirNuevo">Añadir</button>

    <!-- Modal alta/edición -->
    <div v-if="editando" class="modal-overlay" @click="editando = null">
      <form class="modal" @click.stop @submit.prevent="guardar">
        <div class="modal-head">{{ editando.id ? 'Editar certificación' : 'Nueva certificación' }}</div>
        <div class="modal-body">
          <div class="modal-campo">
            <label for="m-conocimiento">Conocimiento / Certificación</label>
            <input id="m-conocimiento" v-model="form.conocimiento" autofocus />
          </div>
          <div class="modal-campo">
            <label for="m-empresa">Empresa emisora</label>
            <input id="m-empresa" v-model="form.empresaEmisora" />
          </div>
          <div class="modal-campo">
            <label for="m-fecha">Fecha</label>
            <input id="m-fecha" type="date" v-model="form.fecha" />
          </div>
          <span v-if="formError" class="perfil-error">{{ formError }}</span>
        </div>
        <div class="modal-foot">
          <button type="button" class="btn" @click="editando = null">Cancelar</button>
          <button type="submit" class="btn btn-primary" :disabled="formBusy">Guardar</button>
        </div>
      </form>
    </div>

    <!-- Modal borrado -->
    <div v-if="borrando" class="modal-overlay" @click="borrando = null">
      <div class="modal" @click.stop>
        <div class="modal-head">Eliminar certificación</div>
        <div class="modal-texto">¿Seguro que quieres eliminar «{{ borrando.conocimiento }}»?</div>
        <div class="modal-foot">
          <button class="btn" @click="borrando = null">Cancelar</button>
          <button class="btn btn-danger" @click="confirmarBorrado">Eliminar</button>
        </div>
      </div>
    </div>
  </div>
</template>
