// frontend-react/src/components/Vacaciones.jsx
import { useState } from 'react';
import {
  MESES, DIAS_SEMANA, DEMO, buildMonth, dateKey, dayFlags, todayKey,
} from '../lib/vacaciones.js';

function Mes({ year, monthIndex, hoy }) {
  const cells = buildMonth(year, monthIndex);
  return (
    <div className="cal-mes">
      <div className="cal-mes-nombre">{MESES[monthIndex]}</div>
      <div className="cal-tabla">
        {DIAS_SEMANA.map((d) => (
          <div className="cal-cab" key={d}>{d}</div>
        ))}
        {cells.map((day, i) => {
          if (day === null) return <div key={`v-${i}`} />;
          const key = dateKey(year, monthIndex, day);
          const f = dayFlags(key, year);
          const clases = ['cal-dia'];
          if (f.holiday) clases.push('festivo');
          if (f.used) clases.push('usado');
          if (f.selected) clases.push('marcado');
          if (key === hoy) clases.push('hoy');
          return (
            <div className={clases.join(' ')} key={key}>{day}</div>
          );
        })}
      </div>
    </div>
  );
}

export default function Vacaciones() {
  const [year, setYear] = useState(DEMO.year);
  const [toast, setToast] = useState(false);
  const hoy = todayKey();
  const r = DEMO.resumen;

  function solicitar() {
    setToast(true);
    setTimeout(() => setToast(false), 2500);
  }

  return (
    <div>
      <div className="vac-yearbar">
        <button className="vac-arrow" onClick={() => setYear(year - 1)} aria-label="Año anterior">‹</button>
        <div className="vac-years">
          <button className="vac-year-side" onClick={() => setYear(year - 1)}>{year - 1}</button>
          <span className="vac-year">{year}</span>
          <button className="vac-year-side" onClick={() => setYear(year + 1)}>{year + 1}</button>
        </div>
        <button className="vac-arrow" onClick={() => setYear(year + 1)} aria-label="Año siguiente">›</button>
      </div>

      <div className="vac-grid">
        {MESES.map((_, m) => (
          <Mes key={m} year={year} monthIndex={m} hoy={hoy} />
        ))}
      </div>

      <div className="vac-resumen">
        <div className="vac-fila">
          <div className="vac-seg amarillo">Acumulados año anterior no disfrutados: {r.acumulados}</div>
          <div className="vac-seg azul">Naturales: {r.naturales} días</div>
        </div>
        <div className="vac-fila">
          <div className="vac-seg rojo">Utilizados: {r.utilizados} días</div>
          <div className="vac-seg verde">Disponibles: {r.disponibles} días</div>
        </div>
      </div>

      <div className="vac-leyenda">
        <span><i className="vac-punto amarillo" /> Acumulados</span>
        <span><i className="vac-punto azul" /> Totales</span>
        <span><i className="vac-punto rojo" /> Utilizados</span>
        <span><i className="vac-punto verde" /> Disponibles</span>
      </div>

      <div className="vac-solicitar">
        <button onClick={solicitar}>Solicitar</button>
        {toast && <div className="vac-toast">La solicitud de vacaciones no está disponible en esta demo.</div>}
      </div>
    </div>
  );
}

// frontend-vue/src/components/Vacaciones.vue
<script setup>
import { ref } from 'vue';
import {
  MESES, DIAS_SEMANA, DEMO, buildMonth, dateKey, dayFlags, todayKey,
} from '../lib/vacaciones.js';

const year = ref(DEMO.year);
const toast = ref(false);
const hoy = todayKey();
const resumen = DEMO.resumen;

function clasesDia(monthIndex, day) {
  const key = dateKey(year.value, monthIndex, day);
  const f = dayFlags(key, year.value);
  return {
    'cal-dia': true,
    festivo: f.holiday,
    usado: f.used,
    marcado: f.selected,
    hoy: key === hoy,
  };
}

function solicitar() {
  toast.value = true;
  setTimeout(() => { toast.value = false; }, 2500);
}
</script>

<template>
  <div>
    <div class="vac-yearbar">
      <button class="vac-arrow" aria-label="Año anterior" @click="year--">‹</button>
      <div class="vac-years">
        <button class="vac-year-side" @click="year--">{{ year - 1 }}</button>
        <span class="vac-year">{{ year }}</span>
        <button class="vac-year-side" @click="year++">{{ year + 1 }}</button>
      </div>
      <button class="vac-arrow" aria-label="Año siguiente" @click="year++">›</button>
    </div>

    <div class="vac-grid">
      <div v-for="(mes, m) in MESES" :key="m" class="cal-mes">
        <div class="cal-mes-nombre">{{ mes }}</div>
        <div class="cal-tabla">
          <div v-for="d in DIAS_SEMANA" :key="d" class="cal-cab">{{ d }}</div>
          <template v-for="(day, i) in buildMonth(year, m)" :key="i">
            <div v-if="day === null" />
            <div v-else :class="clasesDia(m, day)">{{ day }}</div>
          </template>
        </div>
      </div>
    </div>

    <div class="vac-resumen">
      <div class="vac-fila">
        <div class="vac-seg amarillo">Acumulados año anterior no disfrutados: {{ resumen.acumulados }}</div>
        <div class="vac-seg azul">Naturales: {{ resumen.naturales }} días</div>
      </div>
      <div class="vac-fila">
        <div class="vac-seg rojo">Utilizados: {{ resumen.utilizados }} días</div>
        <div class="vac-seg verde">Disponibles: {{ resumen.disponibles }} días</div>
      </div>
    </div>

    <div class="vac-leyenda">
      <span><i class="vac-punto amarillo" /> Acumulados</span>
      <span><i class="vac-punto azul" /> Totales</span>
      <span><i class="vac-punto rojo" /> Utilizados</span>
      <span><i class="vac-punto verde" /> Disponibles</span>
    </div>

    <div class="vac-solicitar">
      <button @click="solicitar">Solicitar</button>
      <div v-if="toast" class="vac-toast">La solicitud de vacaciones no está disponible en esta demo.</div>
    </div>
  </div>
</template>
